# Используем базовый образ python:3.9-slim
FROM python:3.9-slim

# Устанавливаем переменную окружения для корректной работы с Unicode
ENV PYTHONUNBUFFERED 1

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем зависимости проекта
COPY requirements.txt /app/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы проекта
COPY . /app/

# Указываем команду для запуска приложения
CMD ["python", "app.py"]
Dockerfile.python
