version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: web-app
    container_name: web-container
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  db:
    image: mysql:8
    container_name: db-container
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

networks:
  backend:
    name: practice_for_docker_backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
